### ISSUE TITLE
Disqus

### ISSUE THREAD

**Issue by GuyliannEngels** [DylDelp/dylan-delporte-blog#2]
Salut @DylDelp ,

Tu n'as pas encore ajouté disqus sur ton site ne tarde pas

**Comment by DylDelp** [comment]
Coucou , j'ai ajouté disqus et ça fonctionne
________________________________
De : Guyliann Engels <notifications@github.com>
Envoyé : mardi 22 octobre 2019 10:38
À : DylDelp/dylan-delporte-blog <dylan-delporte-blog@noreply.github.com>
Cc : Dylan DELPORTE <Dylan.DELPORTE@student.umons.ac.be>; Mention <mention@noreply.github.com>
Objet : [DylDelp/dylan-delporte-blog] Disqus (#2)


Salut @DylDelp<https://github.com/DylDelp> ,

Tu n'as pas encore ajouté disqus sur ton site ne tarde pas

**Comment by GuyliannEngels** [comment]
Parfait :)
