### ISSUE TITLE
Bug au niveau du YAML des articles du blog d'anglais

### ISSUE THREAD

**Issue by GuyliannEngels** [DylDelp/dylan-delporte-blog#3]
Salut @DylDelp,

Je crée une Issue afin de discuter de ton petit problème dont tu m'as fait part par mail. Voici ta demande 

> Cher Guyliann , 
Je vous adresse ce mail afin de vous signifier que j'ai rencontré un bug vis à vis des mes articles quand je clique sur knit il me mets un message d'erreur que je n'arrive pas à résoudre et qui empêche d'afficher mes modifications in fine sur mon blog( web).
En lien je vous mets le message d'erreur, j'ai essayé de comparer avec les codes d'autres articles de mes camarades et ils présentent 100% de similitudes pour le préambule, mais eux sont capables d'effectuer un  knit !
Pouvais vous m'aider avant le 18 Novembre ? Si oui dit moi comment 
Veuillez agréer mes sincères salutations dans l'attente d'une réponse qui j'espère sera rapide.

![Screenshot_2019-11-12_18-15-37](https://user-images.githubusercontent.com/33956170/68738503-c2616080-05e6-11ea-80fe-d4f9a4c75792.png)

**Comment by GuyliannEngels** [comment]
@DylDelp ,

Je pense que l'erreur provient du fait que dasn le fichier index.rmd, tu as un argument figure: qui ne sert à rien. Quand je l'ai enlevé ton problème était résolu

- Si j'ai résolu ton problème, ferme cette issue

- Si tu as encore un problème en lien avec cette issue, commente à nouveau cette issue.

**Comment by DylDelp** [comment]
Le problème est résolu, merci beaucoup @GuyliannEngels
